language: python
python:
  - 3.4

install: 
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test
  - pep8 game
  - pylint -dmissing-docstring -dtoo-few-public-methods game
  - nosetests --with-coverage
after_success:
  - coveralls
